### ISSUE TITLE
missing json file

### ISSUE THREAD

**Issue by dazinator** [rebus-org/RebusSamples#38]
Where is this json file?
https://github.com/rebus-org/RebusSamples/blob/master/PubSub/PubSub.Publisher/Program.cs#L22

**Comment by JanRou** [comment]
See line 13 in Program.cs! You sholud have a "rebus_subscriptions.json" file in the root directory of the VS solution.

**Comment by dazinator** [comment]
Aha yes, makes sense ;-)
