### ISSUE TITLE
Multitenancy and Competing Consumers

### ISSUE THREAD

**Issue by RichardMau5** [rebus-org/RebusSamples#5]
I have posted a question on StackOverflow, and I think this is a missing example:
https://stackoverflow.com/questions/57712821/rebus-with-azure-service-bus-competing-consumers-and-multi-tenancy

With the answer I would like to create a new example application, so I can give something back to the open source community.

**Comment by mookid8000** [comment]
Cool! 👍 I'm closing this issue then – we'll talk on SO 😄
