### ISSUE TITLE
Request to update RequestReply example to Rebus 6.4.1

### ISSUE THREAD

**Issue by danielh1** [rebus-org/RebusSamples#9]
Greetings Mogens,

I have been trying out  a few of the **RebusSamples** and found the some of them are using older versions of various Rebus packages.

Could you perhaps update the
https://github.com/rebus-org/RebusSamples/tree/master/RequestReply#requestreply
sample to **Rebus 6.4.1** as there has been numerous improvements to the framework. 

Incidentally, I had stumbled upon this issue :
https://github.com/rebus-org/Rebus.Async/issues/3 and noticed that you suggested using `bus.SendRequest<Reply>` .

Can you *enhance* the sample to use `SendRequest` as well ?

Thanks.

**Comment by mookid8000** [comment]
> Could you perhaps update the
https://github.com/rebus-org/RebusSamples/tree/master/RequestReply#requestreply
sample to Rebus 6.4.1 as there has been numerous improvements to the framework.

Yes 🙂 

> Can you enhance the sample to use SendRequest as well ?

No, because Rebus.Async is a hack, which is not recommended, and using it would not be an improvement.
